config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
  tls:
    rejectUnauthorized: false
  ensure: 
    p95: 2000
    p99: 3000
  plugins:
    expect: {}
  payload:
      path: "../payloads/publicbrowsepaths.csv"
      fields:
      - "path"
      order: sequence
      skipHeader: true